name: PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild \
            -project ara.xcodeproj \
            -scheme ara \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            build
